### PR TITLE
Fixed RegexMatchError: get_throttling_function_name in player 2f238d39

### PR DESCRIPTION
**Pull request by felipeucelli**
## Player [2f238d39](https://www.youtube.com/s/player/2f238d39/player_ias.vflset/en_US/base.js) Changes: 

Pytubefix was capturing the name of the transformation function for the parameter "n", by the function that was after the `.length ||,` however YouTube seems to have changed base.js and now this correspondence no longer exists #276.

The new correspondence looks like this:

```js
a.D && (b = "nn" [+a.D], zM(a), c = a.j[b] || null) && (c = XDa[0](c), a.set(b, c))
```

In this player, the name of the function we need is within index `0` of `XDa`.

This new regex supports this new pattern and maintains compatibility with old patterns.

### CODE REVIEW

**Comment by math-ferr** [comment]
Thanks, this works

**Review by celarain — APPROVED** [review]

**Comment by JuanBindez** [comment]
After updating the cipher, something strange is happening, it seems to be slow, test 8.0rc2

**Comment by JuanBindez** [comment]
on_progress seems to be ending before the download, see if this is real

**Comment by felipeucelli** [comment]
> After updating the cipher, something strange is happening, it seems to be slow, test 8.0rc2

I found a small bug in the implementation of the problematic characters, I submitted a PR with the fix: #281 

The download speed is also normal, in the past the 'n' parameter caused a limitation on the download rate, currently failure to decipher it causes error 403.

> on_progress seems to be ending before the download, see if this is real

For me it's working normally. Pytubefix downloads videos in 10MB blocks, if the file is smaller the progress bar loads instantly.

**Pull request merged**
